# Generated by Django 4.0 on 2021-12-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinFamily',
            fields=[
                ('domain_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clade', models.CharField(max_length=256)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.proteinfamily')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.protein')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.taxonomy')),
            ],
        ),
    ]
