# Generated by Django 4.0 on 2022-01-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256)),
                ('length', models.IntegerField()),
                ('sequence', models.CharField(max_length=400000)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinFamily',
            fields=[
                ('domain_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clade', models.CharField(max_length=256)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.domains')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.taxonomy'),
        ),
        migrations.AddField(
            model_name='domains',
            name='pfam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.proteinfamily'),
        ),
        migrations.AddField(
            model_name='domains',
            name='protein',
            field=models.ManyToManyField(related_name='domains', through='rest_api.ProteinDomainLink', to='rest_api.Protein'),
        ),
        migrations.AddField(
            model_name='domains',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.taxonomy'),
        ),
    ]
