# Generated by Django 4.0 on 2021-12-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.IntegerField()),
                ('clade', models.CharField(max_length=256)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
                ('fk_ProteinFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.proteinfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256)),
                ('sequence', models.CharField(max_length=40000)),
                ('length', models.IntegerField()),
                ('fk_Taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.taxonomy')),
            ],
        ),
    ]
